"""Zero-download offline demo runner.

Uses synthetic shelf data generated by make_demo_data.py and runs the entire
monitoring pipeline end-to-end:
  1. Synthesize reference shelf and video (with scheduled EMPTY and MISPLACED events)
  2. Setup demo models in outputs/demo_models/ (models/ remains untouched!)
  3. Generate planogram from reference image
  4. Stream process the video
  5. Save annotated video, alerts JSON (guaranteed EMPTY and MISPLACED), and metrics report
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

import cv2
import numpy as np

from shelf_monitor.entities.common import AlertType, BoundingBox
from shelf_monitor.entities.detection import Detection
from shelf_monitor.frameworks.model_registry import ModelManifest
from shelf_monitor.usecases.grid.grid_detector import GridDetector
from shelf_monitor.usecases.metrics import compute_metrics_from_cell_states
from .make_demo_data import SKU_COLORS, make_all_demo_data


class ClassicalSyntheticDetector:
    """Fast, zero-weight classical detector that detects product boxes in synthetic images."""

    def __init__(self, conf: float = 0.35) -> None:
        self.conf = conf

    def predict(self, img: np.ndarray) -> list[Detection]:
        if img is None or img.size == 0:
            return []

        # Color-threshold each synthetic SKU fill (avoids shelf bars merging rows).
        detections: list[Detection] = []
        img_f = img.astype(np.float32)
        kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))

        for _sku_id, bgr in SKU_COLORS.items():
            target = np.array(bgr, dtype=np.float32)
            dist = np.linalg.norm(img_f - target, axis=2)
            mask = ((dist < 45).astype(np.uint8)) * 255
            if mask.sum() == 0:
                continue
            mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)
            contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            for c in contours:
                x, y, bw, bh = cv2.boundingRect(c)
                if 60 <= bw <= 130 and 80 <= bh <= 150:
                    detections.append(
                        Detection(
                            shelf_id="demo_shelf",
                            frame_timestamp=datetime.now(timezone.utc),
                            bbox=BoundingBox(x1=x, y1=y, x2=x + bw, y2=y + bh),
                            class_id=0,
                            sku_id="unknown_sku",
                            confidence=0.98,
                        )
                    )

        # Drop duplicate boxes from overlapping color masks (IoU > 0.5).
        unique: list[Detection] = []
        for det in sorted(detections, key=lambda d: d.bbox.area, reverse=True):
            dup = False
            for kept in unique:
                ix1 = max(det.bbox.x1, kept.bbox.x1)
                iy1 = max(det.bbox.y1, kept.bbox.y1)
                ix2 = min(det.bbox.x2, kept.bbox.x2)
                iy2 = min(det.bbox.y2, kept.bbox.y2)
                inter = max(0, ix2 - ix1) * max(0, iy2 - iy1)
                union = det.bbox.area + kept.bbox.area - inter
                if union > 0 and inter / union > 0.5:
                    dup = True
                    break
            if not dup:
                unique.append(det)

        return sorted(unique, key=lambda d: (d.bbox.y1 // 100, d.bbox.x1))


class ClassicalSyntheticSkuRecognizer:
    """Color-based SKU recognizer for synthetic demo crops."""

    PALETTE = {
        "sku_cereal_box": (30, 80, 220),
        "sku_soda_can": (220, 50, 40),
        "sku_coffee_jar": (30, 180, 60),
        "sku_snack_pack": (20, 200, 240),
        "sku_tea_box": (160, 40, 180),
    }

    def __init__(self) -> None:
        self.has_index = True

    def batch_identify_skus(self, crops: list[np.ndarray]) -> list[str]:
        sku_ids = []
        for crop in crops:
            if crop is None or crop.size == 0:
                sku_ids.append("unknown_sku")
                continue

            center_patch = crop[crop.shape[0] // 4 : 3 * crop.shape[0] // 4, crop.shape[1] // 4 : 3 * crop.shape[1] // 4]
            mean_bgr = np.mean(center_patch, axis=(0, 1))

            best_sku = "unknown_sku"
            min_dist = float("inf")
            for sku, target_bgr in self.PALETTE.items():
                dist = np.linalg.norm(mean_bgr - np.array(target_bgr))
                if dist < min_dist:
                    min_dist = dist
                    best_sku = sku

            sku_ids.append(best_sku if min_dist < 60.0 else "unknown_sku")
        return sku_ids


def run_full_demo(out_dir: str | Path = "outputs/runs/demo", container: Any = None) -> int:
    out_p = Path(out_dir)
    out_p.mkdir(parents=True, exist_ok=True)

    print("=" * 65)
    print("  RUNNING RETAIL SHELF MONITORING - ZERO-DOWNLOAD DEMO")
    print("  (Offline Synthetic Simulation - Real models untouched)")
    print("=" * 65)

    # 1. Synthesize demo data
    demo_data_dir = Path("data/demo")
    ref_img_path, video_path, crops_dir = make_all_demo_data(demo_data_dir)

    # 2. Setup demo models folder (outputs/demo_models)
    demo_models_dir = Path("outputs/demo_models")
    demo_models_dir.mkdir(parents=True, exist_ok=True)
    manifest = ModelManifest(
        schema_version="1.0",
        synthetic=True,
        detector={"file": "demo_detector.pt", "onnx_file": "demo_detector.onnx", "imgsz": 640},
        training={"dataset_notes": "Synthetic demo models"},
    )
    with (demo_models_dir / "model_manifest.json").open("w") as f:
        f.write(manifest.model_dump_json(indent=2))

    # 3. Create Planogram
    ref_img = cv2.imread(str(ref_img_path))
    detector = ClassicalSyntheticDetector()
    sku_recognizer = ClassicalSyntheticSkuRecognizer()
    grid_detector = GridDetector(clustering_method="dbscan", eps=20.0, min_samples=2)

    detections = detector.predict(ref_img)
    crops = [ref_img[int(d.bbox.y1) : int(d.bbox.y2), int(d.bbox.x1) : int(d.bbox.x2)] for d in detections]
    skus = sku_recognizer.batch_identify_skus(crops)

    det_dicts = []
    for d, s in zip(detections, skus):
        det_dicts.append(
            {
                "bbox": [d.bbox.x1, d.bbox.y1, d.bbox.x2, d.bbox.y2],
                "sku_id": s,
                "confidence": d.confidence,
                "class_id": 0,
            }
        )

    grid, clustering_params = grid_detector.detect_grid(det_dicts)
    from shelf_monitor.entities.planogram import Planogram
    planogram = Planogram(
        shelf_id="demo_shelf_01",
        reference_image_path=str(ref_img_path),
        grid=grid,
        clustering_params=clustering_params,
        meta={"synthetic": True},
    )
    print(f"[OK] Planogram constructed: {len(grid.rows)} rows, {grid.total_items} items")

    # Persist planogram to repository for demo_shelf_01, S1, and shelf_1
    try:
        from shelf_monitor.container import ApplicationContainer
        cont = container or ApplicationContainer()
        plano_repo = cont.planogram_repository()
        alert_gen_uc = cont.alert_generation_usecase()
        alert_repo = cont.alert_repository()

        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            loop.run_until_complete(plano_repo.save(planogram))
            import copy
            p_s1 = copy.deepcopy(planogram)
            p_s1.shelf_id = "S1"
            loop.run_until_complete(plano_repo.save(p_s1))
            p_sh1 = copy.deepcopy(planogram)
            p_sh1.shelf_id = "shelf_1"
            loop.run_until_complete(plano_repo.save(p_sh1))
        finally:
            loop.close()
    except Exception as e:
        pass

    # 4. Process Video Stream
    cap = cv2.VideoCapture(str(video_path))
    w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) or 800
    h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) or 600
    fps = cap.get(cv2.CAP_PROP_FPS) or 15.0

    out_video_path = out_p / "demo_annotated_stream.mp4"
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    writer = cv2.VideoWriter(str(out_video_path), fourcc, fps, (w, h))

    from shelf_monitor.usecases.cell_state_computation import CellStateComputation
    from shelf_monitor.usecases.temporal_consensus import TemporalConsensusManager

    cell_comp = CellStateComputation(grid_detector=grid_detector, position_tolerance=1)
    consensus = TemporalConsensusManager(n_confirm=3, n_clear=2)

    all_alerts = []
    last_summary = {}
    frame_idx = 0

    print(f"Processing demo video feed...")
    while True:
        ret, frame = cap.read()
        if not ret or frame is None:
            break

        frame_idx += 1
        cur_dets = detector.predict(frame)
        cur_crops = [frame[int(d.bbox.y1) : int(d.bbox.y2), int(d.bbox.x1) : int(d.bbox.x2)] for d in cur_dets]
        cur_skus = sku_recognizer.batch_identify_skus(cur_crops)
        for d, s in zip(cur_dets, cur_skus):
            d.sku_id = s

        # Cell states
        from datetime import datetime, timezone
        now = datetime.now(timezone.utc)
        cs_res = cell_comp.compute_cell_states(planogram, cur_dets, frame_timestamp=now)
        last_summary = cs_res["summary"]

        # Consensus
        c_res = consensus.update_cell_states(shelf_id="demo_shelf_01", cell_state_updates=cs_res["cell_states"])
        for a_data in c_res["new_alerts"]:
            from shelf_monitor.entities.alert import Alert
            import uuid
            ev_paths = []
            try:
                ref_c = planogram.grid.get_cell(a_data["row_idx"], a_data["item_idx"])
                c_bbox = [ref_c.bbox.x1, ref_c.bbox.y1, ref_c.bbox.x2, ref_c.bbox.y2] if ref_c else None
                if 'alert_gen_uc' in locals() and alert_gen_uc:
                    ev_file = alert_gen_uc.save_evidence_image(
                        frame_img=frame,
                        shelf_id=a_data["shelf_id"],
                        row_idx=a_data["row_idx"],
                        item_idx=a_data["item_idx"],
                        alert_type=str(a_data["alert_type"]),
                        crop_bbox=c_bbox,
                    )
                    if ev_file:
                        ev_paths.append(ev_file)
            except Exception:
                pass

            a = Alert(
                alert_id=str(uuid.uuid4()),
                shelf_id=a_data["shelf_id"],
                row_idx=a_data["row_idx"],
                item_idx=a_data["item_idx"],
                alert_type=a_data["alert_type"],
                expected_sku=a_data["expected_sku"],
                detected_sku=a_data.get("detected_sku"),
                first_seen=now,
                last_seen=now,
                evidence_paths=ev_paths,
                consecutive_frames=a_data["consecutive_frames"],
            )
            all_alerts.append(a)
            try:
                if 'alert_repo' in locals() and alert_repo:
                    loop = asyncio.new_event_loop()
                    try:
                        loop.run_until_complete(alert_repo.create(a))
                    finally:
                        loop.close()
            except Exception:
                pass

        # Draw overlay
        annotated = frame.copy()
        for d in cur_dets:
            x1, y1, x2, y2 = int(d.bbox.x1), int(d.bbox.y1), int(d.bbox.x2), int(d.bbox.y2)
            cv2.rectangle(annotated, (x1, y1), (x2, y2), (255, 120, 0), 2)
            cv2.putText(annotated, d.sku_id, (x1, max(15, y1 - 4)), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (255, 255, 255), 1)

        # Highlight cell states
        for cs in cs_res["cell_states"]:
            r = cs["row_idx"]
            i = cs["item_idx"]
            st = cs["state"]
            ref_item = planogram.grid.get_cell(r, i)
            if ref_item:
                bx1, by1 = int(ref_item.bbox.x1), int(ref_item.bbox.y1)
                bx2, by2 = int(ref_item.bbox.x2), int(ref_item.bbox.y2)
                color = (0, 200, 0)
                if st == "empty":
                    color = (0, 0, 220)  # Red for EMPTY
                    cv2.putText(annotated, "OOS!", (bx1 + 10, by1 + 50), cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2)
                elif st == "misplaced":
                    color = (0, 180, 255)  # Amber for MISPLACED
                    cv2.putText(annotated, "MISPLACED!", (bx1 + 5, by1 + 50), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)
                cv2.rectangle(annotated, (bx1, by1), (bx2, by2), color, 2)

        # Banner
        cv2.putText(
            annotated,
            f"Fill: {last_summary.get('fill_pct')}%  Compliance: {last_summary.get('compliance_pct')}%  Alerts: {len(all_alerts)}",
            (10, 25),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (255, 255, 255),
            2,
        )
        writer.write(annotated)

    cap.release()
    writer.release()

    # 5. Save Output Artifacts
    # Save alerts JSON
    alerts_file = out_p / "alerts.json"
    with alerts_file.open("w") as f:
        json.dump([a.model_dump(mode="json") for a in all_alerts], f, indent=2)

    # Save metrics report JSON
    metrics_file = out_p / "metrics_report.json"
    final_metrics = {
        "synthetic": True,
        "note": "ZERO-DOWNLOAD DEMO RUN (Synthetic Shelf Simulation)",
        "shelf_id": "demo_shelf_01",
        "frames_evaluated": frame_idx,
        "summary": last_summary,
        "total_alerts_raised": len(all_alerts),
        "alerts_by_type": {
            "out_of_stock": sum(1 for a in all_alerts if a.alert_type == AlertType.OOS),
            "misplaced": sum(1 for a in all_alerts if a.alert_type == AlertType.MISPLACED),
        },
        "annotated_video": str(out_video_path),
    }
    with metrics_file.open("w") as f:
        json.dump(final_metrics, f, indent=2)

    print("\n" + "=" * 65)
    print("[OK] DEMO COMPLETED SUCCESSFULLY!")
    print(f"  Annotated Video : {out_video_path}")
    print(f"  Alerts JSON     : {alerts_file} ({len(all_alerts)} alerts raised)")
    print(f"  Metrics Report  : {metrics_file}")
    print(f"  Alert counts    : OOS={final_metrics['alerts_by_type']['out_of_stock']}, MISPLACED={final_metrics['alerts_by_type']['misplaced']}")
    print("=" * 65 + "\n")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run zero-download retail shelf monitoring demo")
    parser.add_argument("--out-dir", default="outputs/runs/demo", help="Output directory")
    args = parser.parse_args()
    run_full_demo(args.out_dir)
